openapi: 3.1.0
info:
  title: GearScout Server
  description: GearScout Server
  version: 1.0.0
servers:
  - url: 'https://gearscout.patrickubelhor.com/api/v1'
paths:
  /hello:
    get:
      description: Returns a simple "Hello World" string to check if the server is responsive
      responses:
        '200':
          description: A "Hello World" string.
          content:
            text/plain:
              schema:
                type: string
  /team/{teamNum}/event/{eventCode}:
    get:
      description: Get a team's list of scouted matches for an event
      responses:
        '200':
          content:
            description: A list of matches
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/match'
