import React from 'react';
import { AppState } from '../models';
import { useAppSelector } from '../state';
import {
	ILanguageTranslation,
	Language
} from '@gearscout/models';

const translateKey = (language: string, key: string): string => {
	const mapping = languages[language];

	if (Object.hasOwn(mapping, key)) {
		return mapping[key];
	}

	return key;
};

export const translate = (Component) => {
	function AddTranslator(props) {
		const translate: Translator = useTranslator();
		return <Component translate={ translate } { ...props } />;
	}

	return AddTranslator;
};

type Translator = (key: string) => string;
export const useTranslator = (): Translator => {
	const language: string = useAppSelector((state: AppState) => state.language);

	return (key: string) => translateKey(language, key);
};

const languages: ILanguageTranslation = {
	[Language.ENGLISH]: {
		'SIGN_IN': 'Sign in',
		'GAME_YEAR': 'Game year',
		'YOUR_TEAM_NUMBER': 'Your team number',
		'TEAM_NUMBER': 'Team number',
		'EVENT_CODE': 'Event code',
		'SECRET_CODE': 'Secret code',
		'LOADING': 'Loading...',
		'MATCH': 'Match',
		'MATCHES': 'Matches',
		'TEAM': 'Team',
		'TEAMS': 'Teams',
		'STATS': 'Stats',
		'PLAN': 'Plan',
		'DATA': 'Data',
		'LANGUAGE': 'Language',
		'LOGOUT': 'Logout',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Select a match to view more details',
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Select a team to view more details',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Select a statistic to view in-depth analysis',
		'NOTES_TABLE': 'Notes table',
		'STATS_TABLE': 'Stats table',
		'COMBINED_STATISTICS': 'Combined Statistics',
		'TOTAL': 'Total',
		'INSPECTIONS_TABLE': 'Inspections table',
		'SUM_LIST': 'Totals',
		'MEAN_LIST': 'Mean list',
		'MEAN': 'Mean',
		'MEDIAN': 'Median',
		'MODE': 'Mode',
		'MAX': 'Max',
		'SCORES': 'Scores',
		'VALUE': 'Value',
		'ACCOUNT': 'Account',
		'DOWNLOAD_DATA': 'Download data',
		'DOWNLOAD_DATA_AS_CSV': 'Download data as a CSV file',
		'CHANGE_LANGUAGE': 'Change language',
		'EXCLUDE_FROM_STATS': 'Exclude match data from team statistics',
		'INCLUDE_IN_STATS': 'Include match data in team statistics',
		'HIDDEN': 'Hidden',
		'AUTO': 'Autonomous',
		'TELEOP': 'Teleop',
		'HIGH_GOAL_2022': 'High Goal',
		'LOW_GOAL_2022': 'Low Goal',
		'MISS_GOAL_2022': 'Missed Shot',
		'MOBILITY_2022': 'Taxi',
		'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Mobility',
		'CHARGE_STATION_2023': 'Charge Station',
		'GRID_2023': 'Grid',
		'BLUE_GRID_2023': 'Grid (blue)',
		'RED_GRID_2023': 'Grid (red)',
		'NORMALIZED_GRID_2023': 'Normalized Grid',
		'HIGH_GOAL_2024': 'Speaker',
		'LOW_GOAL_2024': 'Amp',
		'PASS_2024': 'Pass',
		'MOBILITY_2024': 'Mobility',
		'CLIMB_2024': 'Climb',
		'ENDGAME_2024': 'Trap',
		'MOBILITY_2025': 'Mobility',
		'LOW_GOAL_2025': 'Processor',
		'HIGH_GOAL_2025': 'Net',
		'ALGAE_REM_2025': 'Algae Removed',
		'CORAL_ONE_2025': 'L1',
		'CORAL_TWO_2025': 'L2',
		'CORAL_THREE_2025': 'L3',
		'CORAL_FOUR_2025': 'L4',
		'CLIMB_2025': 'Barge',
		'ADD_NOTE': 'Add Note',
		'CANCEL': 'Cancel',
		'SUBMIT': 'Submit',
		'IMAGE': 'Image',
		'NOTE': 'Note',
		'NOTES': 'Notes',
		'VIEW_NOTES_FOR_THIS_TEAM': 'View notes for this team',
		'VIEW_IMAGE_OF_ROBOT': 'View image of this robot',
		'NO_QUANTITATIVE_DATA': 'No quantitative data for this team',
		'USERNAME': 'Username',
		'APPLY': 'Apply',
		'CLEAR': 'Clear',
		'CLOSE': 'Close',
		'SEARCH': 'Search',
		'FAILED_TO_LOAD_STATS': 'Failed to load stats',
		'FAILED_TO_LOAD_NOTES': 'Failed to load notes',
		'FAILED_TO_LOAD_IMAGE': 'Failed to load image',
		'FAILED_TO_LOAD_TEAMS': 'Failed to load teams',
		'FAILED_TO_LOAD_MATCHES': 'Failed to load matches',
		'FAILED_TO_LOAD_INSPECTIONS': 'Failed to load inspections',
		'DRIVETRAIN': 'Drivetrain',
		'PROGRAMMING_LANGUAGE': 'Programming language',
		'GAMEPIECE_PREF': 'Gamepiece preference',
		'REFRESH_DATA': 'Refresh data',
		'TABLE_SETTINGS': 'Table settings',
		'SHOW_COLUMNS': 'Show columns',
		'INSPECTIONS': 'Inspections',
		'INSPECTION': 'Inspection',
		'NO_INSPECTION_PERFORMED_ON_ROBOT': 'No inspection has been performed on this robot',
		'ROBOT_OF_TEAM': 'Robot of team {TEAM_NUMBER}',
		'DRIVER_NOTES': 'Driver notes',
		'ROBOT_NOTES': 'Robot notes',
		'SCORE_LOCATIONS': 'Score locations',
		'AUTO_PATHS': 'Auto paths',
		'COMMENTS': 'Comments',
		'ALL': 'All',
		'TOPIC': 'Topic',
		'NO_COMMENTS_FOR_TOPIC': 'There are no comments on this topic',
		'CLIMB_CAPABILITIES': 'Climb capabilities',
		'COLLECTOR_TYPE': 'Collector type',
		'DRIVE_MOTOR_TYPE': 'Drive motor type',
		'INTAKE_LOCATIONS': 'Intake locations',
		'SHOOTING_LOCATIONS': 'Shooting locations',
		'UNDER_STAGE': 'Can go under stage',
		'VISION_CAPABILITIES': 'Vision capabilities',
		'WEIGHT': 'Weight',
		'SELECT_AN_EVENT': 'Select an event',
		'LOAD_EVENT': 'Load event',
		'FAILED_TO_LOAD_EVENTS': 'Failed to load events',
		'GUEST_LOGIN': 'Guest sign in',
		'MEMBER_LOGIN': 'Member sign in',
		'CREATE_ACCOUNT': 'Create account',
		'GUEST': 'Guest',
		'EMAIL': 'Email',
		'PASSWORD': 'Password',
		'EVENTS': 'Events',
		'SWITCH_EVENTS': 'Switch events',
		'RETRY': 'Retry',
		'INTAKE_LOCATIONS_CORAL': 'Coral intake locations',
		'INTAKE_LOCATIONS_ALGAE': 'Algae intake locations',
		'REMOVE_ALGAE': 'Can remove algae',
		'HUMAN_POSITION': 'Preferred HP role'
	},
	[Language.SPANISH]: {
		'SIGN_IN': 'Iniciar sesión',
		'GAME_YEAR': 'Año del juego',
		'YOUR_TEAM_NUMBER': 'Tu numero de equipo',
		'TEAM_NUMBER': 'Numero de equipo',
		'EVENT_CODE': 'Código del evento',
		'SECRET_CODE': 'Código secreto',
		'LOADING': 'Está cargando...',
		'MATCH': 'Partido',
		'MATCHES': 'Partidos',
		'TEAM': 'Equipo',
		'TEAMS': 'Equipos',
		'STATS': 'Estadísticas',
		'PLAN': 'Planificar',
		'DATA': 'Datos',
		'LANGUAGE': 'Lengua',
		'LOGOUT': 'Cerrar sesión',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Seleccione un partido para ver más detalles',
		'NOTES_TABLE': 'Tabla de notas',
		'STATS_TABLE': 'Tabla de estadisticas',
		'COMBINED_STATISTICS': 'Estadísticas combinadas',
		'TOTAL': 'Total',
		'INSPECTIONS_TABLE': 'Table de inspecciones',
		'SUM_LIST': 'Totales',
		'MEAN_LIST': 'Lista media',
		'MEAN': 'Media',
		'MEDIAN': 'Mediana',
		'MODE': 'Moda',
		'MAX': 'Máxima',
		'SCORES': 'Anotaciones',
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Seleccione un equipo para ver más detalles',
		'VALUE': 'Valor',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Seleccione una estadística para ver un análisis en profundidad',
		'ACCOUNT': 'Cuenta',
		'DOWNLOAD_DATA': 'Descargar datos',
		'DOWNLOAD_DATA_AS_CSV': 'Descargar datos como archivo CSV',
		'CHANGE_LANGUAGE': 'Cambiar idioma',
		'EXCLUDE_FROM_STATS': 'Excluir datos de partidos de las estadísticas del equipo',
		'INCLUDE_IN_STATS': 'Incluir datos de partidos en las estadísticas del equipo',
		'HIDDEN': 'Oculto',
		'AUTO': 'Auto',
		'TELEOP': 'Teleop',
		'HIGH_GOAL_2022': 'Núcleo Superior',
		'LOW_GOAL_2022': 'Núcleo Inferior',
		'MISS_GOAL_2022': 'Tiro fallado',
		'MOBILITY_2022': 'Desplazamiento',
		'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Mobilización',
		'CHARGE_STATION_2023': 'Estación de Carga',
		'GRID_2023': 'Portería',
		'BLUE_GRID_2023': 'Portería (azul)',
		'RED_GRID_2023': 'Portería (rojo)',
		'NORMALIZED_GRID_2023': 'Portería Normalizado',
		'HIGH_GOAL_2024': 'Altavoz',
		'LOW_GOAL_2024': 'Amp',
		'PASS_2024': 'Pasar',
		'MOBILITY_2024': 'Salida', // "Leave"
		'CLIMB_2024': 'Escenario', // "Stage"
		'ENDGAME_2024': 'Trampa',
		'MOBILITY_2025': 'Salida',
		'LOW_GOAL_2025': 'Procesador',
		'HIGH_GOAL_2025': 'Red',
		'ALGAE_REM_2025': 'Algas Eliminadas',
		'CORAL_ONE_2025': 'L1',
		'CORAL_TWO_2025': 'L2',
		'CORAL_THREE_2025': 'L3',
		'CORAL_FOUR_2025': 'L4',
		'CLIMB_2025': 'Barca',
		'ADD_NOTE': 'Añadir la Nota',
		'CANCEL': 'Cancelar',
		'SUBMIT': 'Entregar',
		'IMAGE': 'Imagen',
		'NOTE': 'Nota',
		'NOTES': 'Notas',
		'VIEW_NOTES_FOR_THIS_TEAM': 'Ver notas de este equipo',
		'VIEW_IMAGE_OF_ROBOT': 'Ver imagen de este robot',
		'NO_QUANTITATIVE_DATA': 'No hay datos cuantitativos para este equipo',
		'USERNAME': 'Nombre de usuario',
		'APPLY': 'Aplicar',
		'CLEAR': 'Despejar',
		'CLOSE': 'Cerrar',
		'SEARCH': 'Buscar',
		'FAILED_TO_LOAD_STATS': 'Error al cargar estadísticas',
		'FAILED_TO_LOAD_NOTES': 'Error al cargar notas',
		'FAILED_TO_LOAD_IMAGE': 'Error al cargar la imagen',
		'FAILED_TO_LOAD_TEAMS': 'Error al cargar los equipos',
		'FAILED_TO_LOAD_MATCHES': 'Error al cargar los partidos',
		'FAILED_TO_LOAD_INSPECTIONS': 'Error al cargar las inspecciones',
		'DRIVETRAIN': 'Transmisión',
		'PROGRAMMING_LANGUAGE': 'Lenguaje de programación',
		'GAMEPIECE_PREF': 'Preferencia de piezas de juego',
		'REFRESH_DATA': 'Actualizar datos',
		'TABLE_SETTINGS': 'Configuración de la mesa',
		'SHOW_COLUMNS': 'Mostrar columnas',
		'INSPECTIONS': 'Inspecciones',
		'INSPECTION': 'Inspección',
		'NO_INSPECTION_PERFORMED_ON_ROBOT': 'No se ha realizado ninguna inspección en este robot',
		'ROBOT_OF_TEAM': 'Robot del equipo {TEAM_NUMBER}',
		'DRIVER_NOTES': 'Notas sobre los conductores',
		'ROBOT_NOTES': 'Notas sobre el robot',
		'SCORE_LOCATIONS': 'Lugares para marcando',
		'AUTO_PATHS': 'Caminos para auto',
		'COMMENTS': 'Comentarios',
		'ALL': 'Todas',
		'TOPIC': 'Tema',
		'NO_COMMENTS_FOR_TOPIC': 'No hay comentarios en este tema',
		'CLIMB_CAPABILITIES': 'Capacidades de ascenso',
		'COLLECTOR_TYPE': 'Tipo de coleccionista',
		'DRIVE_MOTOR_TYPE': 'Tipo de motor de accionamiento',
		'INTAKE_LOCATIONS': 'Lugares de recogida',
		'SHOOTING_LOCATIONS': 'Lugares de disparo',
		'UNDER_STAGE': 'Puede pasar bajo el escenario',
		'VISION_CAPABILITIES': 'Capacidades de visión',
		'WEIGHT': 'Peso',
		'SELECT_AN_EVENT': 'Seleccione un evento',
		'LOAD_EVENT': 'Cargue el evento',
		'FAILED_TO_LOAD_EVENTS': 'No se pudieron cargar los eventos',
		'GUEST_LOGIN': 'Iniciar sesión como invitado',
		'MEMBER_LOGIN': 'Iniciar sesión como miembro',
		'CREATE_ACCOUNT': 'Crear una cuenta',
		'GUEST': 'Invitado',
		'EMAIL': 'Correo electrónico',
		'PASSWORD': 'Contraseña',
		'EVENTS': 'Eventos',
		'SWITCH_EVENTS': 'Cambiar el evento',
		'RETRY': 'Rever',
		'INTAKE_LOCATIONS_CORAL': 'Lugares de captación de corales',
		'INTAKE_LOCATIONS_ALGAE': 'Lugares de captación de algas',
		'REMOVE_ALGAE': 'Puede eliminar las algas',
		'HUMAN_POSITION': 'Rol de jugador humano preferido'
	},
	[Language.FRENCH]: {
		'SIGN_IN': 'Connexion',
		'GAME_YEAR': 'Année de jeu',
		'YOUR_TEAM_NUMBER': 'Votre numéro d\'équipe',
		'TEAM_NUMBER': 'Numéro d\'équipe',
		'EVENT_CODE': 'Code de l\'événement',
		'SECRET_CODE': 'Code secret',
		'LOADING': 'C\'est en cours de chargement...',
		'MATCH': 'Match',
		'MATCHES': 'Matchs',
		'TEAM': 'Équipe',
		'TEAMS': 'Équipes',
		'STATS': 'Statistiques',
		'PLAN': 'Planifier',
		'DATA': 'Les données',
		'LANGUAGE': 'Langue',
		'LOGOUT': 'Se déconnecter',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Sélectionnez une match pour afficher plus de détails',
		'NOTES_TABLE': 'Tableau des notes',
		'STATS_TABLE': 'Tableau statistique',
		'COMBINED_STATISTICS': 'Statistiques combinées',
		'TOTAL': 'Total',
		'INSPECTIONS_TABLE': 'Tableau des inspections',
		'SUM_LIST': 'Totaux',
		'MEAN_LIST': 'Liste moyenne',
		'MEAN': 'Moyenne',
		'MEDIAN': 'Médiane',
		'MODE': 'Mode',
		'MAX': 'Maximum',
		'SCORES': 'Pointages',
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Sélectionnez une équipe pour afficher plus de détails',
		'VALUE': 'Évaluer',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Sélectionnez une statistique pour afficher une analyse approfondie',
		'ACCOUNT': 'Compte',
		'DOWNLOAD_DATA': 'Télécharger les données',
		'DOWNLOAD_DATA_AS_CSV': 'Télécharger les données sous forme de fichier CSV',
		'CHANGE_LANGUAGE': 'Changer de langue',
		'EXCLUDE_FROM_STATS': 'Exclure les données de match des statistiques de l\'équipe',
		'INCLUDE_IN_STATS': 'Inclure les données de match dans les statistiques de l\'équipe',
		'HIDDEN': 'Caché',
		'AUTO': 'Auto',
		'TELEOP': 'Téléop',
		'HIGH_GOAL_2022': 'Centre de tri supérieur',
		'LOW_GOAL_2022': 'Centre de tri inférieur',
		'MISS_GOAL_2022': 'Coup raté',
		'MOBILITY_2022': 'Circulation',
		'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Mobilité',
		'CHARGE_STATION_2023': 'Station de recharge',
		'GRID_2023': 'Réseau',
		'BLUE_GRID_2023': 'Réseau (bleu)',
		'RED_GRID_2023': 'Réseau (rouge)',
		'NORMALIZED_GRID_2023': 'Réseau normalisé',
		'HIGH_GOAL_2024': 'Haut-parleur',
		'LOW_GOAL_2024': 'Ampli',
		'PASS_2024': 'Passer',
		'MOBILITY_2024': 'Départ',
		'CLIMB_2024': 'Scène',
		'ENDGAME_2024': 'Trappe',
		'MOBILITY_2025': 'Départ',
		'LOW_GOAL_2025': 'Processeur',
		'HIGH_GOAL_2025': 'Filet',
		'ALGAE_REM_2025': 'Algues Éliminées',
		'CORAL_ONE_2025': 'L1',
		'CORAL_TWO_2025': 'L2',
		'CORAL_THREE_2025': 'L3',
		'CORAL_FOUR_2025': 'L4',
		'CLIMB_2025': 'Barge',
		'ADD_NOTE': 'Ajouter une note',
		'CANCEL': 'Annuler',
		'SUBMIT': 'Soumettre',
		'IMAGE': 'Image',
		'NOTE': 'Note',
		'NOTES': 'Notes',
		'VIEW_NOTES_FOR_THIS_TEAM': 'Afficher les notes de cette équipe',
		'VIEW_IMAGE_OF_ROBOT': 'Afficher l\'image de ce robot',
		'NO_QUANTITATIVE_DATA': 'Pas de données quantitatives pour cette équipe',
		'USERNAME': 'Nom d\'utilisateur',
		'APPLY': 'Appliquer',
		'CLEAR': 'Supprimer',
		'CLOSE': 'Fermer',
		'SEARCH': 'Chercher',
		'FAILED_TO_LOAD_STATS': 'Échec du chargement des statistiques',
		'FAILED_TO_LOAD_NOTES': 'Échec du chargement des notes',
		'FAILED_TO_LOAD_IMAGE': 'Échec du chargement de l\'image',
		'FAILED_TO_LOAD_TEAMS': 'Échec du chargement des équipes',
		'FAILED_TO_LOAD_MATCHES': 'Échec du chargement des matchs',
		'FAILED_TO_LOAD_INSPECTIONS': 'Échec du chargement des inspections',
		'DRIVETRAIN': 'Transmission',
		'PROGRAMMING_LANGUAGE': 'Langage de programmation',
		'GAMEPIECE_PREF': 'Préférence de pièce de jeu',
		'REFRESH_DATA': 'Recharger les données',
		'TABLE_SETTINGS': 'Paramètres du tableau',
		'SHOW_COLUMNS': 'Afficher les colonnes',
		'INSPECTIONS': 'Inspections',
		'INSPECTION': 'Inspection',
		'NO_INSPECTION_PERFORMED_ON_ROBOT': 'Aucune inspection n\'a été effectuée sur ce robot',
		'ROBOT_OF_TEAM': 'Robot de l\'équipe {TEAM_NUMBER}',
		'DRIVER_NOTES': 'Remarques sur les pilotes',
		'ROBOT_NOTES': 'Remarques sur le robot',
		'SCORE_LOCATIONS': 'Emplacements de marquer',
		'AUTO_PATHS': 'Trajectoire pour auto',
		'COMMENTS': 'Commentaires',
		'ALL': 'Tous',
		'TOPIC': 'Sujet',
		'NO_COMMENTS_FOR_TOPIC': 'Il n\'y a pas de commentaires sur ce sujet',
		'CLIMB_CAPABILITIES': 'Capacités d\'escalade',
		'COLLECTOR_TYPE': 'Type de collecteur',
		'DRIVE_MOTOR_TYPE': 'Type de moteur d\'entraînement',
		'INTAKE_LOCATIONS': 'Lieux de ramassage',
		'SHOOTING_LOCATIONS': 'Lieux de tir',
		'UNDER_STAGE': 'Peut passer sous scène',
		'VISION_CAPABILITIES': 'Capacités visuelles',
		'WEIGHT': 'Poids',
		'SELECT_AN_EVENT': 'Sélectionnez un événement',
		'LOAD_EVENT': 'Charge l\'événement',
		'FAILED_TO_LOAD_EVENTS': 'Échec du chargement des événements',
		'GUEST_LOGIN': 'Connexion invité',
		'MEMBER_LOGIN': 'Connexion membre',
		'CREATE_ACCOUNT': 'Créer un compte',
		'GUEST': 'Invité',
		'EMAIL': 'E-mail',
		'PASSWORD': 'Mot de passe',
		'EVENTS': 'Événements',
		'SWITCH_EVENTS': 'Changer l\'événement',
		'RETRY': 'Réessayer',
		'INTAKE_LOCATIONS_CORAL': 'Emplacements des prises d\'eau de corail',
		'INTAKE_LOCATIONS_ALGAE': 'Emplacements de captage des algues',
		'REMOVE_ALGAE': 'Peut éliminer les algues',
		'HUMAN_POSITION': 'Rôle de joueur humain préféré'
	},
	[Language.TURKISH]: {
		'SIGN_IN': 'Kayıt olmak',
		'GAME_YEAR': 'Oyun yılı',
		'YOUR_TEAM_NUMBER': 'Takım numaranız',
		'TEAM_NUMBER': 'Takım numarası',
		'EVENT_CODE': 'Etkinlik kodu',
		'SECRET_CODE': 'Gizli kod',
		'LOADING': 'Yükleniyor...',
		'MATCH': 'Maç',
		'MATCHES': 'Maçlar',
		'TEAM': 'Takım',
		'TEAMS': 'Takımlar',
		'STATS': 'Istatistikler',
		'PLAN': 'Planlamak',
		'DATA': 'Veri',
		'LANGUAGE': 'Dilim',
		'LOGOUT': 'Çıkış yap',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Daha fazla ayrıntı görmek için bir eşleşme seçin',
		'NOTES_TABLE': 'Not tablosu',
		'STATS_TABLE': 'Istatistik tablosu',
		'COMBINED_STATISTICS': 'Birleşik İstatistikler',
		'TOTAL': 'Toplam',
		'INSPECTIONS_TABLE': 'Muayene masası',
		'SUM_LIST': 'Toplamlar',
		'MEAN_LIST': 'Ortalama liste',
		'MEAN': 'Ortalama',
		'MEDIAN': 'Medyan',
		'MODE': 'Mod',
		'MAX': 'Maksimum',
		'SCORES': 'Puanı',
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Daha fazla ayrıntı görmek için bir ekip seçin',
		'VALUE': 'Değer',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Derinlemesine analizi görüntülemek için bir istatistik seçin',
		'ACCOUNT': 'Hesap',
		'DOWNLOAD_DATA': 'Verileri indir',
		'DOWNLOAD_DATA_AS_CSV': 'Verileri CSV dosyası olarak indirin',
		'CHANGE_LANGUAGE': 'Dili değiştir',
		'EXCLUDE_FROM_STATS': 'Maç verilerini takım istatistiklerinden hariç tut',
		'INCLUDE_IN_STATS': 'Takım istatistiklerine maç verilerini dahil et',
		'HIDDEN': 'Gizlenmiş',
		'AUTO': 'Otonom',
		'TELEOP': 'Uzaktan Kontrol',
		'HIGH_GOAL_2022': 'Üst Aktarma Merkez',
		'LOW_GOAL_2022': 'Alt Aktarma Merkezi̇',
		'MISS_GOAL_2022': 'Kaçırılan Gol',
		'MOBILITY_2022': 'Taksi̇',
		'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Hareketli̇li̇k',
		'CHARGE_STATION_2023': 'Şarj İstasyonu',
		'GRID_2023': 'Şebeke',
		'BLUE_GRID_2023': 'Şebeke (mavi)',
		'RED_GRID_2023': 'Şebeke (kırmızı)',
		'NORMALIZED_GRID_2023': 'Normalleştirilmiş Şebeke',
		'HIGH_GOAL_2024': 'Hoparlör',
		'LOW_GOAL_2024': 'Amfi̇',
		'PASS_2024': 'Geçmek',
		'MOBILITY_2024': 'Ayrilma',
		'CLIMB_2024': 'Sahne',
		'ENDGAME_2024': 'Bölme',
		'MOBILITY_2025': 'Ayrilma',
		'LOW_GOAL_2025': 'İşlemci',
		'HIGH_GOAL_2025': 'Ağ',
		'ALGAE_REM_2025': 'Algler Kaldırıldı',
		'CORAL_ONE_2025': 'S1',
		'CORAL_TWO_2025': 'S2',
		'CORAL_THREE_2025': 'S3',
		'CORAL_FOUR_2025': 'S4',
		'CLIMB_2025': 'Tekne',
		'ADD_NOTE': 'Not Ekle',
		'CANCEL': 'İptal etmek',
		'SUBMIT': 'Sunmak',
		'IMAGE': 'Resim',
		'NOTE': 'Not',
		'NOTES': 'Notlar',
		'VIEW_NOTES_FOR_THIS_TEAM': 'Bu ekip için notları görüntüle',
		'VIEW_IMAGE_OF_ROBOT': 'Bu robotun resmini göster',
		'NO_QUANTITATIVE_DATA': 'Bu ekip için nicel veri yok',
		'USERNAME': 'Kullanıcı adı',
		'APPLY': 'Uygula',
		'CLEAR': 'Temizlemek',
		'CLOSE': 'Kapatmak',
		'SEARCH': 'Aramak',
		'FAILED_TO_LOAD_STATS': 'İstatistikler yüklenemedi',
		'FAILED_TO_LOAD_NOTES': 'Notlar yüklenemedi',
		'FAILED_TO_LOAD_IMAGE': 'Resim yüklenemedi',
		'FAILED_TO_LOAD_TEAMS': 'Takımlar yüklenemedi',
		'FAILED_TO_LOAD_MATCHES': 'Maçlar yüklenemedi',
		'FAILED_TO_LOAD_INSPECTIONS': 'Muayeneler yüklenemedi',
		'DRIVETRAIN': 'Aktarma organları',
		'PROGRAMMING_LANGUAGE': 'Programlama dili',
		'GAMEPIECE_PREF': 'Oyun parçası tercihi',
		'REFRESH_DATA': 'Sütunları göster',
		'TABLE_SETTINGS': 'Tablo ayarları',
		'SHOW_COLUMNS': 'Verileri yeniden yükle',
		'INSPECTIONS': 'Muayeneler',
		'INSPECTION': 'Muayene',
		'NO_INSPECTION_PERFORMED_ON_ROBOT': 'Bu robot üzerinde herhangi bir muayene yapılmadı',
		'ROBOT_OF_TEAM': '{TEAM_NUMBER} Takımının Robotu',
		'DRIVER_NOTES': 'Sürücüler hakkında notlar',
		'ROBOT_NOTES': 'Robotla ilgili notlar',
		'SCORE_LOCATIONS': 'Puan aldıkları yerler',
		'AUTO_PATHS': 'Özerk rutinler',
		'COMMENTS': 'Yorumlar',
		'ALL': 'Tüm',
		'TOPIC': 'Konu',
		'NO_COMMENTS_FOR_TOPIC': 'Bu konu hakkında yorum yok',
		'CLIMB_CAPABILITIES': 'Tırmanma yetenekleri',
		'COLLECTOR_TYPE': 'Toplayıcı tipi',
		'DRIVE_MOTOR_TYPE': 'Aktarma organı motor tipi',
		'INTAKE_LOCATIONS': 'Toplama yerleri',
		'SHOOTING_LOCATIONS': 'Ateşleme yerleri',
		'UNDER_STAGE': 'Sahne altına girebilir',
		'VISION_CAPABILITIES': 'Görüş yetenekleri',
		'WEIGHT': 'Ağırlık',
		'SELECT_AN_EVENT': 'Bir etkinlik seçin',
		'LOAD_EVENT': 'Etkinliği yükle',
		'FAILED_TO_LOAD_EVENTS': 'Etkinlikler yüklenemedi',
		'GUEST_LOGIN': 'Misafir girişi',
		'MEMBER_LOGIN': 'Üye girişi',
		'CREATE_ACCOUNT': 'Bir hesap oluşturun',
		'GUEST': 'Misafir',
		'EMAIL': 'E-posta',
		'PASSWORD': 'Şifre',
		'EVENTS': 'Etkinlikler', // TODO verify this or Olaylar
		'SWITCH_EVENTS': 'Etkinliği değiştir',
		'RETRY': 'Tekrar dene',
		'INTAKE_LOCATIONS_CORAL': 'Mercan giriş yerleri',
		'INTAKE_LOCATIONS_ALGAE': 'Alg giriş yerleri',
		'REMOVE_ALGAE': 'Algleri kaldırabilir',
		'HUMAN_POSITION': 'Tercih edilen insan oyuncu rolü'
	},
	[Language.CZECH]: {
		'SIGN_IN': 'Přihlásit se',
		'GAME_YEAR': 'Herní rok',
		'YOUR_TEAM_NUMBER': 'Čislo dvéjo týmu',
		'TEAM_NUMBER': 'Číslo týmu',
		'EVENT_CODE': 'Kód události',
		'SECRET_CODE': 'Tajný kód',
		'LOADING': 'Načítání dat...', // TODO: verify
		'MATCH': 'Zápas',
		'MATCHES': 'Zápasy',
		'TEAM': 'Tým',
		'TEAMS': 'Týmy',
		'STATS': 'Statistika',
		'PLAN': 'Plán',
		'DATA': 'Data',
		'LANGUAGE': 'Jazyk',
		'LOGOUT': 'Odhlásit se',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Výběrem shody zobrazíte další podrobnosti', // TODO: verify
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Chcete-li zobrazit další podrobnosti, vyberte tým',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Chcete-li zobrazit další podrobnosti, vyberte statistiku',
		'NOTES_TABLE': 'Tabulka poznámek',
		'STATS_TABLE': 'Tabulka statistik',
		'COMBINED_STATISTICS': 'Kombinovaná statistika',
		'TOTAL': 'Celkový',
		'INSPECTIONS_TABLE': 'Tabulka prohlídek',
		'SUM_LIST': 'Součty',
		'MEAN_LIST': 'Průměrný seznam',
		'MEAN': 'Průměr',
		'MEDIAN': 'Medián',
		'MODE': 'Modus',
		'MAX': 'Max',
		'SCORES': 'Skóre',
		'VALUE': 'Hodnota',
		'ACCOUNT': 'Účet',
		'DOWNLOAD_DATA': 'Stáhnout data',
		'DOWNLOAD_DATA_AS_CSV': 'Stáhněte si data jako CSV soubor',
		'CHANGE_LANGUAGE': 'Změnit jazyk',
		'EXCLUDE_FROM_STATS': 'Vyloučit ze statistik',
		'INCLUDE_IN_STATS': 'Zahrnout do statistik',
		'HIDDEN': 'Skrytý',
		'AUTO': 'Autonomní',
		'TELEOP': 'Teleoperoval',
		// 'HIGH_GOAL_2022': 'Centre de Tri Supérieur',
		// 'LOW_GOAL_2022': 'Centre de Tri Inférieur',
		// 'MISS_GOAL_2022': 'Coup raté',
		// 'MOBILITY_2022': 'Circulation',
		// 'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Mobilita',
		'CHARGE_STATION_2023': 'Nabíjecí stanice',
		'GRID_2023': 'Mřížka',
		'BLUE_GRID_2023': 'Modrá mřížka',
		'RED_GRID_2023': 'Červená mřížka',
		'NORMALIZED_GRID_2023': 'Normalizovaná mřížka',
		'HIGH_GOAL_2024': 'Reproduktor',
		'LOW_GOAL_2024': 'Zesilovač',
		'PASS_2024': 'Přejít',
		'MOBILITY_2024': 'Odejít',
		'CLIMB_2024': 'Jeviště',
		'ENDGAME_2024': 'Past',
		'MOBILITY_2025': 'Odejít',
		'LOW_GOAL_2025': 'Procesor',
		'HIGH_GOAL_2025': 'Síť',
		'ALGAE_REM_2025': 'Řasy Odstraněny',
		'CORAL_ONE_2025': 'Úroveň Jedna',
		'CORAL_TWO_2025': 'Úroveň Dvě',
		'CORAL_THREE_2025': 'Úroveň Tři',
		'CORAL_FOUR_2025': 'Úroveň Čtyři',
		'CLIMB_2025': 'Bárka',
		'ADD_NOTE': 'Přidat poznámku',
		'CANCEL': 'Zrušení',
		'SUBMIT': 'Předložit',
		'IMAGE': 'Obraz',
		'NOTE': 'Poznámka',
		'NOTES': 'Poznámky',
		'VIEW_NOTES_FOR_THIS_TEAM': 'Zobrazit poznámky pro tento tým',
		'VIEW_IMAGE_OF_ROBOT': 'Zobrazit obrázek tohoto robota',
		'NO_QUANTITATIVE_DATA': 'Pro tento tým neexistují žádná kvantitativní data', // TODO: verify
		'USERNAME': 'Uživatelské jméno',
		'APPLY': 'Aplikovat',
		'CLEAR': 'Vymazat',
		'CLOSE': 'Zavřít',
		'SEARCH': 'Vyhledávání',
		'FAILED_TO_LOAD_STATS': 'Statistiky se nepodařilo načíst',
		'FAILED_TO_LOAD_NOTES': 'Poznámky se nepodařilo načíst',
		'FAILED_TO_LOAD_IMAGE': 'Obrazy se nepodařilo načíst',
		'FAILED_TO_LOAD_TEAMS': 'Týmy se nepodařilo načíst',
		'FAILED_TO_LOAD_MATCHES': 'Zápasy se nepodařilo načíst',
		'FAILED_TO_LOAD_INSPECTIONS': 'Prohlídky se nepodařilo načíst',
		'DRIVETRAIN': 'Hnací ústrojí',
		'PROGRAMMING_LANGUAGE': 'Programovací jazyk',
		'GAMEPIECE_PREF': 'Preferovaný herní kus',
		'REFRESH_DATA': 'Aktualizujte data',
		'TABLE_SETTINGS': 'Nastavení tabulky', // TODO: verify
		'SHOW_COLUMNS': 'Zobrazit sloupce',
		'INSPECTIONS': 'Prohlídky',
		'INSPECTION': 'Prohlídka',
		'NO_INSPECTION_PERFORMED_ON_ROBOT': 'U tohoto robota nebyla provedena žádná prohlídka', // TODO: verify
		// 'DRIVER_NOTES': 'Notas sobre los conductores',
		'ROBOT_NOTES': 'Robot poznámky',
		'SCORE_LOCATIONS': 'Místa bodování',
		'AUTO_PATHS': 'Autonomní cesty',
		'COMMENTS': 'Komentáře',
		'ALL': 'Všechno',
		'TOPIC': 'Téma',
		'NO_COMMENTS_FOR_TOPIC': 'K tomuto tématu nejsou žádné komentáře', // TODO: verify
		'CLIMB_CAPABILITIES': 'Schopnosti stoupání', // TODO verify
		'COLLECTOR_TYPE': 'Typ kolektoru', // TODO verify -> Typ sběrače?
		'DRIVE_MOTOR_TYPE': 'Typ motoru pohonu', // TODO verify
		'INTAKE_LOCATIONS': 'Sběrná místa', // TODO verify
		'SHOOTING_LOCATIONS': 'Místa střelby', // TODO verify
		'UNDER_STAGE': 'Může jít pod jeviště',
		'VISION_CAPABILITIES': 'Schopnosti vidění',
		'WEIGHT': 'Hmotnost',
		'SELECT_AN_EVENT': 'Vyberte událost', // TODO verify
		'LOAD_EVENT': 'Načíst událost', // TODO verify
		'FAILED_TO_LOAD_EVENTS': 'Události se nepodařilo načíst', // TODO verify
		'GUEST_LOGIN': 'Přihlaste se jako host', // TODO verify
		'MEMBER_LOGIN': 'Přihlašte se členem', // TODO verify
		'CREATE_ACCOUNT': 'Vytvořit účet', // TODO verify
		'GUEST': 'Host', // TODO verify
		'EMAIL': 'E-mailem', // TODO verify
		'PASSWORD': 'Heslo', // TODO verify
		'EVENTS': 'Události', // TODO verify
		'SWITCH_EVENTS': 'Přepněte událost', // TODO: verify
		'RETRY': 'Zkuste to znovu',
		'INTAKE_LOCATIONS_CORAL': 'Místa příjmu korálů', // TODO: verify
		'INTAKE_LOCATIONS_ALGAE': 'Místa příjmu řas', // TODO: verify
		'REMOVE_ALGAE': 'Dokáže odstranit řasy', // TODO: verify
		'HUMAN_POSITION': 'Preferovaná role lidského hráče' //TODO: verify
	}
};
