import React from 'react';
import { AppState, ILanguageTranslation, Language } from '../models';
import { useAppSelector } from '../state';

const translateKey = (language: string, key: string): string => {
	const mapping = languages[language];

	if (Object.hasOwn(mapping, key)) {
		return mapping[key];
	}

	return key;
};

export const translate = (Component) => {
	function AddTranslator(props) {
		const translate: Translator = useTranslator();
		return <Component translate={ translate } { ...props } />;
	}

	return AddTranslator;
};

type Translator = (key: string) => string;
export const useTranslator = (): Translator => {
	const language: string = useAppSelector((state: AppState) => state.language);

	return (key: string) => translateKey(language, key);
};

const languages: ILanguageTranslation = {
	[Language.ENGLISH]: {
		'SIGN_IN': 'Sign In',
		'YOUR_TEAM_NUMBER': 'Your team number',
		'TEAM_NUMBER': 'Team number',
		'EVENT_CODE': 'Event code',
		'SECRET_CODE': 'Secret code',
		'LOADING': 'Loading...',
		'MATCH': 'Match',
		'MATCHES': 'Matches',
		'TEAM': 'Team',
		'TEAMS': 'Teams',
		'STATS': 'Stats',
		'PLAN': 'Plan',
		'DATA': 'Data',
		'LANGUAGE': 'Language',
		'LOGOUT': 'Logout',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Select a match to view more details',
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Select a team to view more details',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Select a statistic to view in-depth analysis',
		'NOTES_TABLE': 'Notes table',
		'STATS_TABLE': 'Stats table',
		'INSPECTIONS_TABLE': 'Inspections table',
		'SUM_LIST': 'Totals',
		'MEAN_LIST': 'Mean list',
		'MEAN': 'Mean',
		'MEDIAN': 'Median',
		'MODE': 'Mode',
		'MAX': 'Max',
		'SCORES': 'Scores',
		'VALUE': 'Value',
		'ACCOUNT': 'Account',
		'DOWNLOAD_DATA': 'Download data',
		'DOWNLOAD_DATA_AS_CSV': 'Download data as a CSV file',
		'CHANGE_LANGUAGE': 'Change language',
		'EXCLUDE_FROM_STATS': 'Exclude match data from team statistics',
		'INCLUDE_IN_STATS': 'Include match data in team statistics',
		'HIDDEN': 'Hidden',
		'AUTO': 'Autonomous',
		'TELEOP': 'Teleop',
		'HIGH_GOAL_2022': 'High Goal',
		'LOW_GOAL_2022': 'Low Goal',
		'MISS_GOAL_2022': 'Missed Shot',
		'MOBILITY_2022': 'Taxi',
		'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Mobility',
		'CHARGE_STATION_2023': 'Charge Station',
		'GRID_2023': 'Grid',
		'BLUE_GRID_2023': 'Grid (blue)',
		'RED_GRID_2023': 'Grid (red)',
		'NORMALIZED_GRID_2023': 'Normalized Grid',
		'HIGH_GOAL_2024': 'Speaker',
		'LOW_GOAL_2024': 'Amp',
		'MOBILITY_2024': 'Mobility',
		'CLIMB_2024': 'Climb',
		'ENDGAME_2024': 'Trap',
		'ADD_NOTE': 'Add Note',
		'CANCEL': 'Cancel',
		'SUBMIT': 'Submit',
		'IMAGE': 'Image',
		'NOTE': 'Note',
		'NOTES': 'Notes',
		'VIEW_NOTES_FOR_THIS_TEAM': 'View notes for this team',
		'VIEW_IMAGE_OF_ROBOT': 'View image of this robot',
		'NO_QUANTITATIVE_DATA': 'No quantitative data for this team',
		'USERNAME': 'Username',
		'APPLY': 'Apply',
		'CLEAR': 'Clear',
		'CLOSE': 'Close',
		'SEARCH': 'Search',
		'FAILED_TO_LOAD_STATS': 'Failed to load stats',
		'FAILED_TO_LOAD_NOTES': 'Failed to load notes',
		'FAILED_TO_LOAD_IMAGE': 'Failed to load image',
		'FAILED_TO_LOAD_TEAMS': 'Failed to load teams',
		'FAILED_TO_LOAD_MATCHES': 'Failed to load matches',
		'FAILED_TO_LOAD_INSPECTIONS': 'Failed to load inspections',
		'DRIVETRAIN': 'Drivetrain',
		'PROGRAMMING_LANGUAGE': 'Programming language',
		'GAMEPIECE_PREF': 'Gamepiece preference',
		'REFRESH_DATA': 'Refresh data',
		'TABLE_SETTINGS': 'Table settings',
		'SHOW_COLUMNS': 'Show columns',
		'INSPECTIONS': 'Inspections',
		'ROBOT_OF_TEAM': 'Robot of team {TEAM_NUMBER}',
		'DRIVER_NOTES': 'Driver notes',
		'ROBOT_NOTES': 'Robot notes',
		'SCORE_LOCATIONS': 'Score locations',
		'AUTO_PATHS': 'Auto paths',
		'COMMENTS': 'Comments',
		'ALL': 'All',
		'TOPIC': 'Topic',
		'NO_COMMENTS_FOR_TOPIC': 'There are no comments on this topic'
	},
	[Language.SPANISH]: {
		'SIGN_IN': 'Iniciar sesión',
		'YOUR_TEAM_NUMBER': 'Tu numero de equipo',
		'TEAM_NUMBER': 'Numero de equipo',
		'EVENT_CODE': 'Código del evento',
		'SECRET_CODE': 'Código secreto',
		'LOADING': 'Está cargando...',
		'MATCH': 'Partido',
		'MATCHES': 'Partidos',
		'TEAM': 'Equipo',
		'TEAMS': 'Equipos',
		'STATS': 'Estadísticas',
		'PLAN': 'Planificar',
		'DATA': 'Datos',
		'LANGUAGE': 'Lengua',
		'LOGOUT': 'Cerrar sesión',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Seleccione un partido para ver más detalles',
		'NOTES_TABLE': 'Tabla de notas',
		'STATS_TABLE': 'Tabla de estadisticas',
		'INSPECTIONS_TABLE': 'Table de inspecciones',
		'SUM_LIST': 'Totales',
		'MEAN_LIST': 'Lista media',
		'MEAN': 'Media',
		'MEDIAN': 'Mediana',
		'MODE': 'Moda',
		'MAX': 'Máxima',
		'SCORES': 'Anotaciones',
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Seleccione un equipo para ver más detalles',
		'VALUE': 'Valor',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Seleccione una estadística para ver un análisis en profundidad',
		'ACCOUNT': 'Cuenta',
		'DOWNLOAD_DATA': 'Descargar datos',
		'DOWNLOAD_DATA_AS_CSV': 'Descargar datos como archivo CSV',
		'CHANGE_LANGUAGE': 'Cambiar idioma',
		'EXCLUDE_FROM_STATS': 'Excluir datos de partidos de las estadísticas del equipo',
		'INCLUDE_IN_STATS': 'Incluir datos de partidos en las estadísticas del equipo',
		'HIDDEN': 'Oculto',
		'AUTO': 'Auto',
		'TELEOP': 'Teleop',
		'HIGH_GOAL_2022': 'Núcleo Superior',
		'LOW_GOAL_2022': 'Núcleo Inferior',
		'MISS_GOAL_2022': 'Tiro fallado',
		'MOBILITY_2022': 'Desplazamiento',
		'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Mobilización',
		'CHARGE_STATION_2023': 'Estación de Carga',
		'GRID_2023': 'Portería',
		'BLUE_GRID_2023': 'Portería (azul)',
		'RED_GRID_2023': 'Portería (rojo)',
		'NORMALIZED_GRID_2023': 'Portería Normalizado',
		'HIGH_GOAL_2024': 'Altavoz',
		'LOW_GOAL_2024': 'Amp',
		'MOBILITY_2024': 'Salida', // "Leave"
		'CLIMB_2024': 'Escenario', // "Stage"
		'ENDGAME_2024': 'Trampa',
		'ADD_NOTE': 'Añadir la Nota',
		'CANCEL': 'Cancelar',
		'SUBMIT': 'Entregar',
		'IMAGE': 'Imagen',
		'NOTE': 'Nota',
		'NOTES': 'Notas',
		'VIEW_NOTES_FOR_THIS_TEAM': 'Ver notas de este equipo',
		'VIEW_IMAGE_OF_ROBOT': 'Ver imagen de este robot',
		'NO_QUANTITATIVE_DATA': 'No hay datos cuantitativos para este equipo',
		'USERNAME': 'Nombre de usuario',
		'APPLY': 'Aplicar',
		'CLEAR': 'Despejar',
		'CLOSE': 'Cerrar',
		'SEARCH': 'Buscar',
		'FAILED_TO_LOAD_STATS': 'Error al cargar estadísticas',
		'FAILED_TO_LOAD_NOTES': 'Error al cargar notas',
		'FAILED_TO_LOAD_IMAGE': 'Error al cargar la imagen',
		'FAILED_TO_LOAD_TEAMS': 'Error al cargar los equipos',
		'FAILED_TO_LOAD_MATCHES': 'Error al cargar los partidos',
		'FAILED_TO_LOAD_INSPECTIONS': 'Error al cargar las inspecciones',
		'DRIVETRAIN': 'Transmisión',
		'PROGRAMMING_LANGUAGE': 'Lenguaje de programación',
		'GAMEPIECE_PREF': 'Preferencia de piezas de juego',
		'REFRESH_DATA': 'Actualizar datos',
		'TABLE_SETTINGS': 'Configuración de la mesa',
		'SHOW_COLUMNS': 'Mostrar columnas',
		'INSPECTIONS': 'Inspecciones',
		'ROBOT_OF_TEAM': 'Robot del equipo {TEAM_NUMBER}',
		'DRIVER_NOTES': 'Notas sobre los conductores',
		'ROBOT_NOTES': 'Notas sobre el robot',
		'SCORE_LOCATIONS': 'Lugares para marcando',
		'AUTO_PATHS': 'Caminos para auto',
		'COMMENTS': 'Comentarios',
		'ALL': 'Todas',
		'TOPIC': 'Tema',
		'NO_COMMENTS_FOR_TOPIC': 'No hay comentarios en este tema'
	},
	[Language.FRENCH]: {
		'SIGN_IN': 'Connexion',
		'YOUR_TEAM_NUMBER': 'Votre numéro d\'équipe',
		'TEAM_NUMBER': 'Numéro d\'équipe',
		'EVENT_CODE': 'Code de l\'événement',
		'SECRET_CODE': 'Code secret',
		'LOADING': 'C\'est en cours de chargement...',
		'MATCH': 'Match',
		'MATCHES': 'Matchs',
		'TEAM': 'Équipe',
		'TEAMS': 'Équipes',
		'STATS': 'Statistiques',
		'PLAN': 'Planifier',
		'DATA': 'Les données',
		'LANGUAGE': 'Langue',
		'LOGOUT': 'Se déconnecter',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Sélectionnez une match pour afficher plus de détails',
		'NOTES_TABLE': 'Tableau des notes',
		'STATS_TABLE': 'Tableau statistique',
		'INSPECTIONS_TABLE': 'Tableau des inspections',
		'SUM_LIST': 'Totaux',
		'MEAN_LIST': 'Liste moyenne',
		'MEAN': 'Moyenne',
		'MEDIAN': 'Médiane',
		'MODE': 'Mode',
		'MAX': 'Maximum',
		'SCORES': 'Pointages',
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Sélectionnez une équipe pour afficher plus de détails',
		'VALUE': 'Évaluer',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Sélectionnez une statistique pour afficher une analyse approfondie',
		'ACCOUNT': 'Compte',
		'DOWNLOAD_DATA': 'Télécharger les données',
		'DOWNLOAD_DATA_AS_CSV': 'Télécharger les données sous forme de fichier CSV',
		'CHANGE_LANGUAGE': 'Changer de langue',
		'EXCLUDE_FROM_STATS': 'Exclure les données de match des statistiques de l\'équipe',
		'INCLUDE_IN_STATS': 'Inclure les données de match dans les statistiques de l\'équipe',
		'HIDDEN': 'Caché',
		'AUTO': 'Auto',
		'TELEOP': 'Téléop',
		'HIGH_GOAL_2022': 'Centre de tri supérieur',
		'LOW_GOAL_2022': 'Centre de tri inférieur',
		'MISS_GOAL_2022': 'Coup raté',
		'MOBILITY_2022': 'Circulation',
		'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Mobilité',
		'CHARGE_STATION_2023': 'Station de recharge',
		'GRID_2023': 'Réseau',
		'BLUE_GRID_2023': 'Réseau (bleu)',
		'RED_GRID_2023': 'Réseau (rouge)',
		'NORMALIZED_GRID_2023': 'Réseau normalisé',
		'HIGH_GOAL_2024': 'Haut-parleur',
		'LOW_GOAL_2024': 'Ampli',
		'MOBILITY_2024': 'Départ',
		'CLIMB_2024': 'Scène',
		'ENDGAME_2024': 'Trappe',
		'ADD_NOTE': 'Ajouter une note',
		'CANCEL': 'Annuler',
		'SUBMIT': 'Soumettre',
		'IMAGE': 'Image',
		'NOTE': 'Note',
		'NOTES': 'Notes',
		'VIEW_NOTES_FOR_THIS_TEAM': 'Afficher les notes de cette équipe',
		'VIEW_IMAGE_OF_ROBOT': 'Afficher l\'image de ce robot',
		'NO_QUANTITATIVE_DATA': 'Pas de données quantitatives pour cette équipe',
		'USERNAME': 'Nom d\'utilisateur',
		'APPLY': 'Appliquer',
		'CLEAR': 'Supprimer',
		'CLOSE': 'Fermer',
		'SEARCH': 'Chercher',
		'FAILED_TO_LOAD_STATS': 'Échec du chargement des statistiques',
		'FAILED_TO_LOAD_NOTES': 'Échec du chargement des notes',
		'FAILED_TO_LOAD_IMAGE': 'Échec du chargement de l\'image',
		'FAILED_TO_LOAD_TEAMS': 'Échec du chargement des équipes',
		'FAILED_TO_LOAD_MATCHES': 'Échec du chargement des matchs',
		'FAILED_TO_LOAD_INSPECTIONS': 'Échec du chargement des inspections',
		'DRIVETRAIN': 'Transmission',
		'PROGRAMMING_LANGUAGE': 'Langage de programmation',
		'GAMEPIECE_PREF': 'Préférence de pièce de jeu',
		'REFRESH_DATA': 'Recharger les données',
		'TABLE_SETTINGS': 'Paramètres du tableau',
		'SHOW_COLUMNS': 'Afficher les colonnes',
		'INSPECTIONS': 'Inspections',
		'ROBOT_OF_TEAM': 'Robot de l\'équipe {TEAM_NUMBER}',
		'DRIVER_NOTES': 'Remarques sur les pilotes',
		'ROBOT_NOTES': 'Remarques sur le robot',
		'SCORE_LOCATIONS': 'Emplacements de marquer',
		'AUTO_PATHS': 'Trajectoire pour auto',
		'COMMENTS': 'Commentaires',
		'ALL': 'Tous',
		'TOPIC': 'Sujet',
		'NO_COMMENTS_FOR_TOPIC': 'Il n\'y a pas de commentaires sur ce sujet'
	},
	[Language.TURKISH]: {
		'SIGN_IN': 'Kayıt Olmak',
		'YOUR_TEAM_NUMBER': 'Takım numaranız',
		'TEAM_NUMBER': 'Takım numarası',
		'EVENT_CODE': 'Etkinlik kodu',
		'SECRET_CODE': 'Gizli kod',
		'LOADING': 'Yükleniyor...',
		'MATCH': 'Maç',
		'MATCHES': 'Maçlar',
		'TEAM': 'Takım',
		'TEAMS': 'Takımlar',
		'STATS': 'Istatistikler',
		'PLAN': 'Planlamak',
		'DATA': 'Veri',
		'LANGUAGE': 'Dilim',
		'LOGOUT': 'Çıkış Yap',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Daha fazla ayrıntı görmek için bir eşleşme seçin',
		'NOTES_TABLE': 'Not tablosu',
		'STATS_TABLE': 'Istatistik tablosu',
		'INSPECTIONS_TABLE': 'Muayene masası',
		'SUM_LIST': 'Toplamlar',
		'MEAN_LIST': 'Ortalama liste',
		'MEAN': 'Ortalama',
		'MEDIAN': 'Medyan',
		'MODE': 'Mod',
		'MAX': 'Maksimum',
		'SCORES': 'Puanı',
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Daha fazla ayrıntı görmek için bir ekip seçin',
		'VALUE': 'Değer',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Derinlemesine analizi görüntülemek için bir istatistik seçin',
		'ACCOUNT': 'Hesap',
		'DOWNLOAD_DATA': 'Verileri indir',
		'DOWNLOAD_DATA_AS_CSV': 'Verileri CSV dosyası olarak indirin',
		'CHANGE_LANGUAGE': 'Dili değiştir',
		'EXCLUDE_FROM_STATS': 'Maç verilerini takım istatistiklerinden hariç tut',
		'INCLUDE_IN_STATS': 'Takım istatistiklerine maç verilerini dahil et',
		'HIDDEN': 'Gizlenmiş',
		'AUTO': 'Otonom',
		'TELEOP': 'Uzaktan Kontrol',
		'HIGH_GOAL_2022': 'Üst Aktarma Merkez',
		'LOW_GOAL_2022': 'Alt Aktarma Merkezi̇',
		'MISS_GOAL_2022': 'Kaçırılan Gol',
		'MOBILITY_2022': 'Taksi̇',
		'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Hareketli̇li̇k',
		'CHARGE_STATION_2023': 'Şarj İstasyonu',
		'GRID_2023': 'Şebeke',
		'BLUE_GRID_2023': 'Şebeke (mavi)',
		'RED_GRID_2023': 'Şebeke (kırmızı)',
		'NORMALIZED_GRID_2023': 'Normalleştirilmiş Şebeke',
		'HIGH_GOAL_2024': 'Hoparlör',
		'LOW_GOAL_2024': 'Amfi̇',
		'MOBILITY_2024': 'Ayrilma',
		'CLIMB_2024': 'Sahne',
		'ENDGAME_2024': 'Bölme',
		'ADD_NOTE': 'Not Ekle',
		'CANCEL': 'İptal etmek',
		'SUBMIT': 'Sunmak',
		'IMAGE': 'Resim',
		'NOTE': 'Not',
		'NOTES': 'Notlar',
		'VIEW_NOTES_FOR_THIS_TEAM': 'Bu ekip için notları görüntüle',
		'VIEW_IMAGE_OF_ROBOT': 'Bu robotun resmini göster',
		'NO_QUANTITATIVE_DATA': 'Bu ekip için nicel veri yok',
		'USERNAME': 'Kullanıcı adı',
		'APPLY': 'Uygula',
		'CLEAR': 'Temizlemek',
		'CLOSE': 'Kapatmak',
		'SEARCH': 'Aramak',
		'FAILED_TO_LOAD_STATS': 'İstatistikler yüklenemedi',
		'FAILED_TO_LOAD_NOTES': 'Notlar yüklenemedi',
		'FAILED_TO_LOAD_IMAGE': 'Resim yüklenemedi',
		'FAILED_TO_LOAD_TEAMS': 'Takımlar yüklenemedi',
		'FAILED_TO_LOAD_MATCHES': 'Maçlar yüklenemedi',
		'FAILED_TO_LOAD_INSPECTIONS': 'Muayeneler yüklenemedi',
		'DRIVETRAIN': 'Aktarma organları',
		'PROGRAMMING_LANGUAGE': 'Programlama dili',
		'GAMEPIECE_PREF': 'Oyun parçası tercihi',
		'REFRESH_DATA': 'Sütunları göster',
		'TABLE_SETTINGS': 'Tablo ayarları',
		'SHOW_COLUMNS': 'Verileri yeniden yükle',
		'INSPECTIONS': 'Muayeneler',
		'ROBOT_OF_TEAM': '{TEAM_NUMBER} Takımının Robotu',
		'DRIVER_NOTES': 'Sürücüler hakkında notlar',
		'ROBOT_NOTES': 'Robotla ilgili notlar',
		'SCORE_LOCATIONS': 'Puan aldıkları yerler',
		'AUTO_PATHS': 'Özerk rutinler',
		'COMMENTS': 'Yorumlar',
		'ALL': 'Tüm',
		'TOPIC': 'Konu',
		'NO_COMMENTS_FOR_TOPIC': 'Bu konu hakkında yorum yok'
	},
	[Language.CZECH]: {
		'SIGN_IN': 'Přihlásit se',
		'YOUR_TEAM_NUMBER': 'Čislo dvéjo týmu',
		'TEAM_NUMBER': 'Číslo týmu',
		'EVENT_CODE': 'Kód události',
		'SECRET_CODE': 'Tajný kód',
		'LOADING': 'Načítání dat...', // TODO: verify
		'MATCH': 'Zápas',
		'MATCHES': 'Zápasy',
		'TEAM': 'Tým',
		'TEAMS': 'Týmy',
		'STATS': 'Statistika',
		'PLAN': 'Plán',
		'DATA': 'Data',
		'LANGUAGE': 'Jazyk',
		'LOGOUT': 'Odhlásit se',
		'SELECT_MATCH_VIEW_MORE_DETAILS': 'Výběrem shody zobrazíte další podrobnosti', // TODO: verify
		'SELECT_TEAM_VIEW_MORE_DETAILS': 'Chcete-li zobrazit další podrobnosti, vyberte tým',
		'SELECT_STAT_VIEW_MORE_DETAILS': 'Chcete-li zobrazit další podrobnosti, vyberte statistiku',
		'NOTES_TABLE': 'Tabulka poznámek',
		'STATS_TABLE': 'Tabulka statistik',
		'INSPECTIONS_TABLE': 'Tabulka prohlídek',
		'SUM_LIST': 'Součty',
		'MEAN_LIST': 'Průměrný seznam',
		'MEAN': 'Průměr',
		'MEDIAN': 'Medián',
		'MODE': 'Modus',
		'MAX': 'Max',
		'SCORES': 'Skóre',
		'VALUE': 'Hodnota',
		'ACCOUNT': 'Účet',
		'DOWNLOAD_DATA': 'Stáhnout data',
		'DOWNLOAD_DATA_AS_CSV': 'Stáhněte si data jako CSV soubor',
		'CHANGE_LANGUAGE': 'Změnit jazyk',
		'EXCLUDE_FROM_STATS': 'Vyloučit ze statistik',
		'INCLUDE_IN_STATS': 'Zahrnout do statistik',
		'HIDDEN': 'Skrytý',
		'AUTO': 'Autonomní',
		'TELEOP': 'Teleoperoval',
		// 'HIGH_GOAL_2022': 'Centre de Tri Supérieur',
		// 'LOW_GOAL_2022': 'Centre de Tri Inférieur',
		// 'MISS_GOAL_2022': 'Coup raté',
		// 'MOBILITY_2022': 'Circulation',
		// 'CLIMB_2022': 'Hangar',
		'MOBILITY_2023': 'Mobilita',
		'CHARGE_STATION_2023': 'Nabíjecí stanice',
		'GRID_2023': 'Mřížka',
		'BLUE_GRID_2023': 'Modrá mřížka',
		'RED_GRID_2023': 'Červená mřížka',
		'NORMALIZED_GRID_2023': 'Normalizovaná mřížka',
		'HIGH_GOAL_2024': 'Reproduktor',
		'LOW_GOAL_2024': 'Zesilovač',
		'MOBILITY_2024': 'Odejít',
		'CLIMB_2024': 'Divadlo', // TODO: or jeviště or scéna
		'ENDGAME_2024': 'Trappe',
		'ADD_NOTE': 'Přidat poznámku',
		'CANCEL': 'Zrušení',
		'SUBMIT': 'Předložit',
		'IMAGE': 'Obraz',
		'NOTE': 'Poznámka',
		'NOTES': 'Poznámky',
		'VIEW_NOTES_FOR_THIS_TEAM': 'Zobrazit poznámky pro tento tým',
		'VIEW_IMAGE_OF_ROBOT': 'Zobrazit obrázek tohoto robota',
		'NO_QUANTITATIVE_DATA': 'Pro tento tým neexistují žádná kvantitativní data', // TODO: verify
		'USERNAME': 'Uživatelské jméno',
		'APPLY': 'Aplikovat',
		'CLEAR': 'Vymazat',
		'CLOSE': 'Zavřít',
		'SEARCH': 'Vyhledávání',
		'FAILED_TO_LOAD_STATS': 'Statistiky se nepodařilo načíst',
		'FAILED_TO_LOAD_NOTES': 'Poznámky se nepodařilo načíst',
		'FAILED_TO_LOAD_IMAGE': 'Obrazy se nepodařilo načíst',
		'FAILED_TO_LOAD_TEAMS': 'Týmy se nepodařilo načíst',
		'FAILED_TO_LOAD_MATCHES': 'Zápasy se nepodařilo načíst',
		'FAILED_TO_LOAD_INSPECTIONS': 'Prohlídky se nepodařilo načíst',
		'DRIVETRAIN': 'Hnací ústrojí',
		'PROGRAMMING_LANGUAGE': 'Programovací jazyk',
		'GAMEPIECE_PREF': 'Preferovaný herní kus',
		'REFRESH_DATA': 'Aktualizujte data',
		'TABLE_SETTINGS': 'Nastavení tabulky', // TODO: verify
		'SHOW_COLUMNS': 'Zobrazit sloupce',
		'INSPECTIONS': 'Prohlídky',
		// 'ROBOT_OF_TEAM': 'Robot del equipo {TEAM_NUMBER}',
		// 'DRIVER_NOTES': 'Notas sobre los conductores',
		// 'ROBOT_NOTES': 'Notas sobre el robot',
		// 'SCORE_LOCATIONS': 'Lugares para marcando',
		'AUTO_PATHS': 'Autonomní cesty',
		'COMMENTS': 'Komentáře',
		'ALL': 'Všechno',
		'TOPIC': 'Téma',
		'NO_COMMENTS_FOR_TOPIC': 'K tomuto tématu nejsou žádné komentáře' // TODO: verify
	}
};
