name: Pre-merge Checklist
on:
  pull_request:
    branches:
      - main

jobs:
  Client-Lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /
    steps:
      - run: echo "Current branch = ${{ github.ref }}"
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm ci
        working-directory: client/
      - name: Lint all projects
        run: npx nx run-many -t lint
#        run: npx nx affected -t lint typecheck test build
        working-directory: client/
      - name: Typecheck all projects
        run: npx nx run-many -t typecheck
        working-directory: client/
      - name: Test all projects
        run: npx nx run-many -t test --passWithNoTests true
        working-directory: client/
      - name: Build all projects
        run: npx nx run-many -t build
        working-directory: client/
      - run: echo "This job's status is '${{ job.status }}'"
